use serde::Deserialize;
use serde_json::json;
use similar::{ChangeTag, TextDiff};
use std::{collections::HashSet, io::Write, path::Path};

use git2::{Patch, Repository};

use crate::{
    DiffSession, EXPORT_SIDE_LIMIT, VcsError,
    models::DiffRecord,
    repository::diff::{NativePatchSet, load_text, native_patches},
};

#[derive(Clone, Copy, Debug, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "kebab-case")]
pub enum ExportFormat {
    Markdown,
    Json,
    Xml,
    Txt,
}

impl ExportFormat {
    pub fn extension(self) -> &'static str {
        match self {
            Self::Markdown => "md",
            Self::Json => "json",
            Self::Xml => "xml",
            Self::Txt => "txt",
        }
    }
}

#[derive(Clone, Copy, Debug, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "kebab-case")]
pub enum ExportLayout {
    Split,
    Unified,
    GitPatch,
}

#[derive(Clone, Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ExportOptions {
    pub format: ExportFormat,
    pub layout: ExportLayout,
    pub selected_file_ids: Vec<u32>,
}

pub(crate) fn write_export(
    repository: &Repository,
    workdir: Option<&Path>,
    session: &DiffSession,
    options: &ExportOptions,
    mut writer: impl Write,
) -> Result<(), VcsError> {
    let selected = options
        .selected_file_ids
        .iter()
        .copied()
        .collect::<HashSet<_>>();
    if selected.is_empty() {
        return Err(VcsError::NoFilesSelected);
    }
    let records = session
        .records
        .iter()
        .filter(|record| selected.contains(&record.public.file_id))
        .collect::<Vec<_>>();
    if records.is_empty() {
        return Err(VcsError::NoFilesSelected);
    }
    if records
        .iter()
        .any(|record| record.public.is_binary || record.public.export_too_large)
    {
        return Err(VcsError::UnsupportedExportFile);
    }
    let native_patch_set = (options.layout == ExportLayout::GitPatch)
        .then(|| native_patches(repository, session))
        .transpose()?;

    match options.format {
        ExportFormat::Markdown => {
            writeln!(writer, "# Git Diff Export\n")?;
            writeln!(writer, "> Generated by WinriseF Toolbox\n")?;
            for record in records {
                let content = export_content(
                    repository,
                    workdir,
                    record,
                    options.layout,
                    native_patch_set.as_ref(),
                )?;
                let title = record
                    .public
                    .old_path
                    .as_ref()
                    .map(|old| format!("{} (from {old})", record.public.path))
                    .unwrap_or_else(|| record.public.path.clone());
                writeln!(writer, "## File: {title} ({})\n", record.public.status)?;
                match content {
                    ExportContent::Split { original, modified } => {
                        let language = record.public.path.rsplit('.').next().unwrap_or("txt");
                        if !original.is_empty() {
                            writeln!(
                                writer,
                                "### Original Version\n```{language}\n{original}\n```\n"
                            )?;
                        }
                        if !modified.is_empty() {
                            writeln!(
                                writer,
                                "### Modified Version\n```{language}\n{modified}\n```\n"
                            )?;
                        }
                    }
                    ExportContent::Diff(diff) => {
                        let label = if options.layout == ExportLayout::GitPatch {
                            "Git Patch"
                        } else {
                            "Full Context Diff"
                        };
                        writeln!(writer, "### {label}\n```diff\n{diff}\n```\n")?;
                    }
                }
                writeln!(writer, "---\n")?;
            }
        }
        ExportFormat::Json => {
            writer.write_all(b"{\n  \"generator\": \"WinriseF Toolbox\",\n  \"files\": [\n")?;
            for (index, record) in records.iter().enumerate() {
                if index > 0 {
                    writer.write_all(b",\n")?;
                }
                let content = match export_content(
                    repository,
                    workdir,
                    record,
                    options.layout,
                    native_patch_set.as_ref(),
                )? {
                    ExportContent::Split { original, modified } => {
                        json!({ "original": original, "modified": modified })
                    }
                    ExportContent::Diff(diff) => json!({ "diff": diff }),
                };
                serde_json::to_writer_pretty(
                    &mut writer,
                    &json!({
                        "path": record.public.path,
                        "oldPath": record.public.old_path,
                        "status": record.public.status,
                        "layout": format!("{:?}", options.layout),
                        "content": content,
                    }),
                )?;
            }
            writer.write_all(b"\n  ]\n}\n")?;
        }
        ExportFormat::Xml => {
            writer.write_all(b"<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<git_diff_export generator=\"WinriseF Toolbox\">\n")?;
            for record in records {
                writeln!(
                    writer,
                    "  <file path=\"{}\" old_path=\"{}\" status=\"{}\">",
                    xml_attr(&record.public.path),
                    xml_attr(record.public.old_path.as_deref().unwrap_or_default()),
                    xml_attr(&record.public.status),
                )?;
                match export_content(
                    repository,
                    workdir,
                    record,
                    options.layout,
                    native_patch_set.as_ref(),
                )? {
                    ExportContent::Split { original, modified } => {
                        writeln!(
                            writer,
                            "    <original><![CDATA[\n{}\n]]></original>",
                            cdata(&original)
                        )?;
                        writeln!(
                            writer,
                            "    <modified><![CDATA[\n{}\n]]></modified>",
                            cdata(&modified)
                        )?;
                    }
                    ExportContent::Diff(diff) => {
                        writeln!(writer, "    <diff><![CDATA[\n{}\n]]></diff>", cdata(&diff))?;
                    }
                }
                writer.write_all(b"  </file>\n")?;
            }
            writer.write_all(b"</git_diff_export>\n")?;
        }
        ExportFormat::Txt => {
            writer.write_all(b"WINRISEF TOOLBOX - GIT DIFF EXPORT\n\n")?;
            for record in records {
                writeln!(
                    writer,
                    "=================================================================="
                )?;
                writeln!(
                    writer,
                    "FILE: {}  STATUS: {}",
                    record.public.path, record.public.status
                )?;
                if let Some(old_path) = &record.public.old_path {
                    writeln!(writer, "OLD PATH: {old_path}")?;
                }
                writeln!(
                    writer,
                    "=================================================================="
                )?;
                match export_content(
                    repository,
                    workdir,
                    record,
                    options.layout,
                    native_patch_set.as_ref(),
                )? {
                    ExportContent::Split { original, modified } => {
                        if !original.is_empty() {
                            writeln!(
                                writer,
                                "<<<<<<<< ORIGINAL VERSION START\n{original}\n>>>>>>>> ORIGINAL VERSION END\n"
                            )?;
                        }
                        if !modified.is_empty() {
                            writeln!(
                                writer,
                                "<<<<<<<< MODIFIED VERSION START\n{modified}\n>>>>>>>> MODIFIED VERSION END\n"
                            )?;
                        }
                    }
                    ExportContent::Diff(diff) => writeln!(writer, "{diff}")?,
                }
                writeln!(writer)?;
            }
        }
    }
    Ok(())
}

enum ExportContent {
    Split { original: String, modified: String },
    Diff(String),
}

fn export_content(
    repository: &Repository,
    workdir: Option<&Path>,
    record: &DiffRecord,
    layout: ExportLayout,
    native_patch_set: Option<&NativePatchSet<'_>>,
) -> Result<ExportContent, VcsError> {
    match layout {
        ExportLayout::Split => {
            let (original, modified) = load_export_sides(repository, workdir, record)?;
            Ok(ExportContent::Split { original, modified })
        }
        ExportLayout::Unified => {
            let (original, modified) = load_export_sides(repository, workdir, record)?;
            Ok(ExportContent::Diff(full_context_diff(&original, &modified)))
        }
        ExportLayout::GitPatch => {
            if let Some(native) = native_patch_set
                .and_then(|patches| patches.patch_for(record).transpose())
                .transpose()?
            {
                return Ok(ExportContent::Diff(native));
            }
            let (original, modified) = load_export_sides(repository, workdir, record)?;
            Ok(ExportContent::Diff(buffer_patch(
                record, &original, &modified,
            )?))
        }
    }
}

fn load_export_sides(
    repository: &Repository,
    workdir: Option<&Path>,
    record: &DiffRecord,
) -> Result<(String, String), VcsError> {
    Ok((
        load_text(repository, workdir, &record.original, EXPORT_SIDE_LIMIT)?,
        load_text(repository, workdir, &record.modified, EXPORT_SIDE_LIMIT)?,
    ))
}

fn full_context_diff(original: &str, modified: &str) -> String {
    let diff = TextDiff::from_lines(original, modified);
    let mut output = String::new();
    for change in diff.iter_all_changes() {
        output.push(match change.tag() {
            ChangeTag::Delete => '-',
            ChangeTag::Insert => '+',
            ChangeTag::Equal => ' ',
        });
        output.push_str(change.value());
    }
    output
}

fn buffer_patch(record: &DiffRecord, original: &str, modified: &str) -> Result<String, VcsError> {
    let old_path = record
        .public
        .old_path
        .as_deref()
        .unwrap_or(&record.public.path);
    let mut patch = Patch::from_buffers(
        original.as_bytes(),
        Some(Path::new(old_path)),
        modified.as_bytes(),
        Some(Path::new(&record.public.path)),
        None,
    )?;
    let bytes = patch.to_buf()?;
    String::from_utf8(bytes.as_ref().to_vec()).map_err(|_| VcsError::InvalidText)
}

fn xml_attr(value: &str) -> String {
    value
        .replace('&', "&amp;")
        .replace('"', "&quot;")
        .replace('\'', "&apos;")
        .replace('<', "&lt;")
        .replace('>', "&gt;")
}

fn cdata(value: &str) -> String {
    value.replace("]]>", "]]]]><![CDATA[>")
}
